### Przydatne dane

In [ ]:
# 1. kombinacja klawiszy, ktore uruchmiają wszystkie kody to: shift + enter. Tu nie trzeba, tak jak w SQL zaznaczać całej linii, wystarczy, że kursor się tam znajdzie

# 2. Jak chcemy tworzyć komentarze, to tą linię, która ma być komentarzem, zaznaczamy jako 'Markdown' - opcja w pasku u góry. Już po zapisaniu komentarza, żeby go odpalić, muszę wcisnąć funkcję uruchmiającą: shift+enter

# 3. Jak chcemy dodać nową linię kodu, nie ciąg dalszy jakiejś konkretnej, ale całkiem nwoą, to najeżdzamy kursorem na przerwę miedzy dwoma osobnymi liniami kou i wtedy pojawia się 'Add Code Cell'(czyli linia kodu) albo 'Add Markdown cell', czyli komentarz

In [9]:
print('hello  world')

hello  world


### Import biblioteki numpy

In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

### Pierwsze tablice NumPy

<h1>kod - da sięuzywać w MarkDonw HTMLa</h1>

### Tablica 1D

In [13]:
arr1d = np.array([1, 2, 3])  #mamy zadeklarowaną tablice 1 wymiarową - arr1d
arr1d

array([1, 2, 3])

In [4]:
type(arr1d)  #jaki typ zmiennej w tablicy 1-wymiarowej - ma jeden nawias kwadratowy

numpy.ndarray

### Tablica 2D

In [8]:
arr2d = np.array([[1, 2], [3, 4]])  # tablica 2-wymiarowa - ma dwa nawiasy kwadratowe
arr2d

array([[1, 2],
       [3, 4]])

In [16]:
arr2d

array([[1, 2],
       [3, 4]])

### Tablica 3D

In [5]:
arr3d = np.array([[[1, 2], [3, 4]], [[4, 5],[6, 7]]]) # - ma trzy nawias kwadratowy
arr3d

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

## Wymiary tablic

In [6]:
arr1d.ndim

1

In [9]:
arr2d.ndim

2

In [ ]:
arr3d.ndim

### Kształty Tablicy - ich wymiarowość

arr1d.shape

In [10]:
arr2d.shape

(2, 2)

In [11]:
arr3d.shape

(2, 2, 2)

### Typy danych jakie są wewnątrz tablic

In [14]:
arr1d.dtype # mamy 32 bitowy integer

dtype('int32')

In [16]:
arr_float = np.array([1.1, 2.9]) #nowa tablica ze zmienną float
arr_float

array([1.1, 2.9])

In [17]:
arr_float.dtype

dtype('float64')

In [18]:
arr_bool = np.array([True,False]) #nowa tablica ze zmienną bool
arr_bool

array([ True, False])

In [19]:
arr_bool.dtype

dtype('bool')

In [20]:
arr_int = np.array([1.5, 2.4], dtype='int')#nowa tablica ze zmienną float, ale zadeklarowlaismy że chcemy przechowyać w tej tablicy wartosci nie float, ale initger
arr_int

array([1, 2])

In [21]:
arr_int.dtype

dtype('int32')

### Funkcje tworzące tablice

In [22]:
np.arange(1, 11) # zmiana co jeden

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.arange(1, 20, 3) # zmiana co trzy - ten osttani parametr

array([ 1,  4,  7, 10, 13, 16, 19])

In [24]:
np.zeros(3) # tu mamy tablice 1-wymairową, która ma 3 elementy o wartości 0

array([0., 0., 0.])

In [25]:
np.zeros([2, 3]) # tu mamy tablice 2-wymairową, która ma 6 elementy o wartości 0

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones([2,3]) # tu mamy tablice 2-wymairową, która ma 6 elementy o wartości 1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [28]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [29]:
np.full([2,2], 3) # uzyskamy tablice 2 na 2, ktora będzie wypelniona trojkami

array([[3, 3],
       [3, 3]])

### Podstawowe operacje na tablicach

In [31]:
a = np.array([3,4,5,6]) # tworzymy dwie tablice a i b
b = np.array([-1, 2, 4, 1])

In [32]:
print(a) # teraz wyświetlamy te tablice
print(b)

[3 4 5 6]
[-1  2  4  1]


In [33]:
a + b # ponizej dodajemy, odejmujemy i mnozymy tablice

array([2, 6, 9, 7])

In [34]:
a - b

array([4, 2, 1, 5])

In [ ]:
a * b

In [ ]:
a + 1 # dokazdego elem. tabl. a zostanie dodane 1

### Generowanie liczb pseudolosowych

In [35]:
np.random.seed(5)

In [36]:
np.random.randn()

0.44122748688504143

In [ ]:
np.random.rand()

In [39]:
np.random.randn(10)

array([-0.85685315, -0.87187918, -0.42250793,  0.99643983,  0.71242127,
        0.05914424, -0.36331088,  0.00328884, -0.10593044,  0.79305332])

In [41]:
np.random.randint(10, 20)

15

In [42]:
np.random.choice(['a', 'b', 'c', 'd']) # losuje nam 1 wartośc z tej tablicy

'd'