In [21]:
import numpy as np

In [2]:
arr = np.arange(1, 16) # tworzymy tablice 'arr'
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Wybór elementu po indeksie

In [6]:
arr[2] #z racji, ze indeksy zaczynaja sie od 0, to mamy wartosc 3, kt ra jest równ indeksowi 2

3

In [7]:
arr[2:5]

array([3, 4, 5])

In [8]:
arr[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

### Przypisywanie nowej wartości

In [7]:
arr # patrzy,my jak nasza tablica arr wygląda

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
arr[0] = 100 # w indeksie 0, zmenilismy wartość z 1 na 100
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15])

In [12]:
arr[10:12] = 200
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10, 200, 200,  13,
        14,  15])

### Zmiana kształtu

In [13]:
arr = np.arange(1, 16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
arr2d = arr.reshape([3, 5])
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### Maski logiczne

In [23]:
arr_rnd = np.random.randn(3,5)
arr_rnd

array([[-0.37687542, -1.4756136 , -1.06398026,  1.77442222,  1.75845413],
       [ 0.37465887,  0.67421469,  1.16244222,  0.22863846,  0.14419992],
       [-0.41764817, -0.33726051,  0.81935191, -1.95421559,  0.07924408]])

In [24]:
arr_bool = arr_rnd >0 # to jest maska na powyższą tablicę, ktorej zadaniem jest przefiltrowanie tej powyzeszj tablicy które wartosi są dodanmit ktore ujemne
arr_bool

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False,  True, False,  True]])

In [25]:
arr_rnd[arr_bool]

array([1.77442222, 1.75845413, 0.37465887, 0.67421469, 1.16244222,
       0.22863846, 0.14419992, 0.81935191, 0.07924408])

In [26]:
arr_rnd[arr_rnd > 0]

array([1.77442222, 1.75845413, 0.37465887, 0.67421469, 1.16244222,
       0.22863846, 0.14419992, 0.81935191, 0.07924408])

In [27]:
arr_rnd [arr_rnd < 0]

array([-0.37687542, -1.4756136 , -1.06398026, -0.41764817, -0.33726051,
       -1.95421559])